import type { QuizQuestion, CryptoArea } from "@/types/quiz"

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "experience",
    type: "multiple-choice",
    question: "What is your experience with cryptocurrencies?",
    description: "This helps us understand your current knowledge level",
    options: [
      "Complete Beginner - Heard of Bitcoin but that's it",
      "Some Knowledge - Understand basics but haven't invested",
      "Moderate Experience - Have bought and held some crypto",
      "Experienced - Actively trade and understand DeFi",
    ],
    required: true,
  },
  {
    id: "risk-tolerance",
    type: "slider",
    question: "How comfortable are you with potential losses?",
    description: "Crypto investments can be volatile. Rate your risk tolerance.",
    min: 1,
    max: 10,
    step: 1,
    required: true,
  },
  {
    id: "time-commitment",
    type: "multiple-choice",
    question: "How much time can you dedicate daily to crypto activities?",
    description: "Different strategies require different time investments",
    options: [
      "Less than 30 mins - Want passive approaches",
      "30-60 mins - Can check markets and research",
      "1-3 hours - Willing to manage positions actively",
      "3+ hours - Want to be deeply involved in trading",
    ],
    required: true,
  },
  {
    id: "capital-amount",
    type: "multiple-choice",
    question: "How much are you looking to invest initially?",
    description: "This helps us recommend appropriate strategies",
    options: [
      "Less than $100 - Just starting out",
      "$100-$1,000 - Testing the waters",
      "$1,000-$10,000 - Serious but cautious",
      "Over $10,000 - Ready to make significant moves",
    ],
    required: true,
  },
  {
    id: "learning-style",
    type: "multiple-choice",
    question: "How do you prefer to learn new things?",
    description: "This helps us match you with the right complexity level",
    options: [
      "Simple & Direct - Just tell me what to do",
      "Step-by-step Guides - I like detailed instructions",
      "Research & Experiment - I enjoy figuring things out",
      "Community & Discussion - I learn best from others",
    ],
    required: true,
  },
  {
    id: "goals",
    type: "multiple-choice",
    question: "What is your primary goal with crypto?",
    description: "Understanding your objectives helps us tailor recommendations",
    options: [
      "Long-term Wealth - Set and forget",
      "Passive Income - Earn while holding",
      "Active Trading Gains - Profit from price movements",
      "Learn & Explore - Understand the technology",
    ],
    required: true,
  },
  {
    id: "tech-comfort",
    type: "rating",
    question: "How comfortable are you with technology?",
    description: "Rate your comfort level with apps, wallets, and new platforms",
    min: 1,
    max: 5,
    required: true,
  },
  {
    id: "market-volatility",
    type: "multiple-choice",
    question: "How would you react to a 50% drop in your investment?",
    description: "Crypto markets can be extremely volatile",
    options: [
      "Panic and sell immediately",
      "Feel stressed but hold",
      "Stay calm and wait it out",
      "Buy more at the lower price",
    ],
    required: true,
  },
]

export const CRYPTO_AREAS: Record<string, CryptoArea> = {
  spotHolding: {
    id: "spotHolding",
    name: "Spot Holding",
    description: "Buy and hold major cryptocurrencies for long-term growth",
    riskLevel: "low",
    timeCommitment: "minimal",
    capitalRequirement: "low",
    tags: ["beginner", "long-term", "passive", "bitcoin", "ethereum"],
    detailedDescription:
      "Perfect for beginners who want to invest in crypto without complexity. Simply buy Bitcoin, Ethereum, or other major assets and hold them for the long term. This strategy requires minimal time and technical knowledge while offering exposure to crypto growth potential.",
    difficulty: "beginner",
  },
  airdrops: {
    id: "airdrops",
    name: "Airdrop Farming",
    description: "Earn free tokens by using new protocols and platforms",
    riskLevel: "low",
    timeCommitment: "moderate",
    capitalRequirement: "low",
    tags: ["free-tokens", "early-adopter", "research", "defi", "new-projects"],
    detailedDescription:
      "Get free crypto by being an early user of new protocols. This involves testing new platforms, making transactions, and participating in testnets. While it requires time, it can be very rewarding with minimal financial risk.",
    difficulty: "intermediate",
  },
  defi: {
    id: "defi",
    name: "DeFi Yield Farming",
    description: "Earn yield by providing liquidity and staking in DeFi protocols",
    riskLevel: "medium",
    timeCommitment: "moderate",
    capitalRequirement: "medium",
    tags: ["yield", "staking", "liquidity", "passive-income", "smart-contracts"],
    detailedDescription:
      "Generate passive income by lending your crypto, providing liquidity to exchanges, or staking tokens. Offers attractive yields but requires understanding smart contract risks and impermanent loss.",
    difficulty: "advanced",
  },
  futuresTrading: {
    id: "futuresTrading",
    name: "Futures Trading",
    description: "Trade crypto derivatives with leverage for amplified gains",
    riskLevel: "high",
    timeCommitment: "high",
    capitalRequirement: "medium",
    tags: ["leverage", "derivatives", "active-trading", "technical-analysis", "high-risk"],
    detailedDescription:
      "Advanced trading strategy using leverage to amplify potential gains (and losses). Requires deep market knowledge, technical analysis skills, and active monitoring. High risk but potentially high reward for experienced traders.",
    difficulty: "advanced",
  },
  nfts: {
    id: "nfts",
    name: "NFT Trading & Creation",
    description: "Trade digital collectibles and create NFT projects",
    riskLevel: "high",
    timeCommitment: "high",
    capitalRequirement: "medium",
    tags: ["collectibles", "art", "gaming", "community", "creative"],
    detailedDescription:
      "Participate in the NFT ecosystem by trading digital collectibles, creating your own NFTs, or investing in NFT projects. Highly speculative but offers creative and community-driven opportunities.",
    difficulty: "intermediate",
  },
  memeCoins: {
    id: "memeCoins",
    name: "Meme Coin Trading",
    description: "Trade viral and community-driven cryptocurrencies",
    riskLevel: "high",
    timeCommitment: "high",
    capitalRequirement: "low",
    tags: ["viral", "community", "high-volatility", "social-media", "speculative"],
    detailedDescription:
      "Trade cryptocurrencies that gain popularity through social media and community hype. Extremely volatile and speculative, but can offer massive gains for those who catch trends early.",
    difficulty: "intermediate",
  },
}
